// Code generated by protoc-gen-go.
// source: program.proto
// DO NOT EDIT!

/*
Package pool is a generated protocol buffer package.

It is generated from these files:
	program.proto

It has these top-level messages:
	Program
*/
package pool

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Program struct {
	Name       string   `protobuf:"bytes,1,opt,name=Name" json:"Name,omitempty"`
	Location   string   `protobuf:"bytes,2,opt,name=Location" json:"Location,omitempty"`
	UI         bool     `protobuf:"varint,3,opt,name=UI" json:"UI,omitempty"`
	Key        []byte   `protobuf:"bytes,4,opt,name=Key,proto3" json:"Key,omitempty"`
	Port       uint32   `protobuf:"varint,5,opt,name=Port" json:"Port,omitempty"`
	Start      bool     `protobuf:"varint,6,opt,name=Start" json:"Start,omitempty"`
	Implements []string `protobuf:"bytes,7,rep,name=Implements" json:"Implements,omitempty"`
}

func (m *Program) Reset()                    { *m = Program{} }
func (m *Program) String() string            { return proto.CompactTextString(m) }
func (*Program) ProtoMessage()               {}
func (*Program) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Program) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Program) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *Program) GetUI() bool {
	if m != nil {
		return m.UI
	}
	return false
}

func (m *Program) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *Program) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *Program) GetStart() bool {
	if m != nil {
		return m.Start
	}
	return false
}

func (m *Program) GetImplements() []string {
	if m != nil {
		return m.Implements
	}
	return nil
}

func init() {
	proto.RegisterType((*Program)(nil), "pool.Program")
}

func init() { proto.RegisterFile("program.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 177 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8e, 0xcf, 0x8a, 0xc2, 0x30,
	0x10, 0x87, 0x49, 0xff, 0x77, 0xd8, 0x2e, 0xcb, 0xb0, 0x87, 0x61, 0x0f, 0x4b, 0xf0, 0x94, 0x93,
	0x17, 0x9f, 0xa2, 0x28, 0x52, 0x22, 0x7d, 0x80, 0x28, 0x41, 0x84, 0xa6, 0x13, 0x62, 0x2e, 0x3e,
	0x90, 0xef, 0x29, 0x4d, 0x41, 0xbc, 0x7d, 0xdf, 0x07, 0x33, 0xfc, 0xa0, 0xf3, 0x81, 0xaf, 0xc1,
	0xb8, 0xad, 0x0f, 0x1c, 0x19, 0x0b, 0xcf, 0x3c, 0x6d, 0x9e, 0x02, 0xea, 0x61, 0xed, 0x88, 0x50,
	0x1c, 0x8d, 0xb3, 0x24, 0xa4, 0x50, 0xad, 0x4e, 0x8c, 0x7f, 0xd0, 0x1c, 0xf8, 0x62, 0xe2, 0x8d,
	0x67, 0xca, 0x52, 0x7f, 0x3b, 0x7e, 0x43, 0x36, 0xf6, 0x94, 0x4b, 0xa1, 0x1a, 0x9d, 0x8d, 0x3d,
	0xfe, 0x40, 0xbe, 0xb7, 0x0f, 0x2a, 0xa4, 0x50, 0x5f, 0x7a, 0xc1, 0xe5, 0xe3, 0xc0, 0x21, 0x52,
	0x29, 0x85, 0xea, 0x74, 0x62, 0xfc, 0x85, 0xf2, 0x14, 0x4d, 0x88, 0x54, 0xa5, 0xc3, 0x55, 0xf0,
	0x1f, 0xa0, 0x77, 0x7e, 0xb2, 0xce, 0xce, 0xf1, 0x4e, 0xb5, 0xcc, 0x55, 0xab, 0x3f, 0xca, 0xb9,
	0x4a, 0xa3, 0x77, 0xaf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x76, 0x5f, 0xb5, 0x99, 0xc5, 0x00, 0x00,
	0x00,
}
